import { LayerType } from "./domain";

// trainingData is based on real sequences from pipelines in Noodlr
export const trainingData: LayerType[][] = [
    ['launcher', 'manualDataEntry', 'transformerFillMask', 'dataViewer'],
    ['launcher', 'manualDataEntry', 'transformerFillMask', 'dataViewer'],
    ['launcher', 'manualDataEntry', 'transformerFillMask', 'dataViewer'],
    ['launcher', 'manualDataEntry', 'transformerFillMask', 'dataViewer'],
    ['launcher', 'manualDataEntry', 'transformerFillMask', 'dataViewer'],
    ['launcher', 'manualDataEntry', 'transformerSentimentAnalysis', 'dataViewer'],
    ['launcher', 'manualDataEntry', 'transformerSentimentAnalysis', 'dataViewer'],
    ['launcher', 'manualDataEntry', 'transformerSentimentAnalysis', 'dataViewer'],
    ['launcher', 'manualDataEntry', 'transformerSentimentAnalysis', 'dataViewer'],
    ['launcher', 'manualDataEntry', 'transformerSentimentAnalysis', 'dataViewer'],
    ['launcher', 'manualDataEntry', 'transformerSummarization', 'dataViewer'],
    ['launcher', 'manualDataEntry', 'transformerSummarization', 'dataViewer'],
    ['launcher', 'manualDataEntry', 'transformerSummarization', 'dataViewer'],
    ['launcher', 'manualDataEntry', 'transformerSummarization', 'dataViewer'],
    ['launcher', 'manualDataEntry', 'transformerSummarization', 'dataViewer'],
    ['launcher', 'manualDataEntry', 'transformerFillMask', 'transformerSentimentAnalysis', 'dataViewer'],
    ['launcher', 'manualDataEntry', 'transformerFillMask', 'transformerSentimentAnalysis', 'dataViewer'],
    ['launcher', 'manualDataEntry', 'transformerFillMask', 'transformerSentimentAnalysis', 'dataViewer'],
    ['launcher', 'manualDataEntry', 'transformerFillMask', 'transformerSentimentAnalysis', 'dataViewer'],
    ['launcher', 'manualDataEntry', 'transformerFillMask', 'transformerSentimentAnalysis', 'dataViewer'],
    ['launcher', 'manualDataEntry', 'transformerSummarization', 'transformerSentimentAnalysis', 'dataViewer'],
    ['launcher', 'manualDataEntry', 'transformerSummarization', 'transformerSentimentAnalysis', 'dataViewer'],
    ['launcher', 'manualDataEntry', 'transformerSummarization', 'transformerSentimentAnalysis', 'dataViewer'],
    ['launcher', 'manualDataEntry', 'transformerSummarization', 'transformerSentimentAnalysis', 'dataViewer'],
    ['launcher', 'manualDataEntry', 'transformerSummarization', 'transformerSentimentAnalysis', 'dataViewer'],
    ['dataset', 'rowSplit', 'columnSplit', 'training'],
    ['dataset', 'rowSplit', 'columnSplit', 'training'],
    ['dataset', 'rowSplit', 'columnSplit', 'training'],
    ['dataset', 'rowSplit', 'columnSplit', 'training'],
    ['dataset', 'rowSplit', 'columnSplit', 'training'],
    ['dataset', 'rowSplit', 'columnSplit', 'dense', 'dense', 'training'],
    ['dataset', 'rowSplit', 'columnSplit', 'dense', 'dense', 'training'],
    ['dataset', 'rowSplit', 'columnSplit', 'dense', 'dense', 'training'],
    ['dataset', 'rowSplit', 'columnSplit', 'dense', 'dense', 'training'],
    ['dataset', 'rowSplit', 'columnSplit', 'dense', 'dense', 'training'],
    ['dataset', 'rowSplit', 'columnSplit', 'dense', 'dense', 'training'],
    ['dataset', 'rowSplit', 'columnSplit', 'dense', 'dense', 'training'],
    ['dataset', 'rowSplit', 'columnSplit', 'dense', 'dense', 'dense', 'training'],
    ['dataset', 'rowSplit', 'columnSplit', 'dense', 'dense', 'dense', 'training'],
    ['dataset', 'rowSplit', 'columnSplit', 'dense', 'dense', 'dense', 'training'],
    ['dataset', 'rowSplit', 'columnSplit', 'dense', 'dense', 'dense', 'training'],
    ['dataset', 'rowSplit', 'columnSplit', 'dense', 'dense', 'dense', 'training'],
    ['dataset', 'rowSplit', 'columnSplit', 'dense', 'dense', 'dense', 'training'],
    ['dataset', 'rowSplit', 'columnSplit', 'dense', 'dense', 'dense', 'training'],
    ['dataset', 'rowSplit', 'columnSplit', 'dense', 'dense', 'dense', 'training'],
    ['dataset', 'rowSplit', 'columnSplit', 'dense', 'dense', 'dense', 'training'],
    ['dataset', 'rowSplit', 'columnSplit', 'dense', 'dense', 'dense', 'training'],
    ['dataset', 'rowSplit', 'columnSplit', 'dense', 'dense', 'dense', 'training'],
    ['dataset', 'rowSplit', 'columnSplit', 'dense', 'dense', 'dense', 'training'],
    ['dataset', 'rowSplit', 'columnSplit', 'dense', 'dense', 'dense', 'training'],
    ['dataset', 'rowSplit', 'columnSplit', 'dense', 'dense', 'dense', 'training'],
    ['dataset', 'rowSplit', 'columnSplit', 'dense', 'dense', 'dense', 'training'],
    ['dataset', 'rowSplit', 'columnSplit', 'dense', 'dense', 'dense', 'training'],
    ['dataset', 'rowSplit', 'columnSplit', 'dense', 'dense', 'dense', 'training'],
    ['dataset', 'rowSplit', 'columnSplit', 'dense', 'dense', 'dense', 'training'],
    ['dataset', 'rowSplit', 'columnSplice', 'training'],
    ['dataset', 'rowSplit', 'columnSplice', 'training'],
    ['dataset', 'rowSplit', 'columnSplice', 'training'],
    ['dataset', 'rowSplit', 'columnSplice', 'training'],
    ['dataset', 'rowSplit', 'columnSplice', 'training'],
    ['dataset', 'rowSplit', 'columnSplice', 'dense', 'dense', 'training'],
    ['dataset', 'rowSplit', 'columnSplice', 'dense', 'dense', 'training'],
    ['dataset', 'rowSplit', 'columnSplice', 'dense', 'dense', 'training'],
    ['dataset', 'rowSplit', 'columnSplice', 'dense', 'dense', 'training'],
    ['dataset', 'rowSplit', 'columnSplice', 'dense', 'dense', 'training'],
    ['dataset', 'rowSplit', 'columnSplice', 'dense', 'dense', 'training'],
    ['dataset', 'rowSplit', 'columnSplice', 'dense', 'dense', 'training'],
    ['dataset', 'rowSplit', 'columnSplice', 'dense', 'dense', 'dense', 'training'],
    ['dataset', 'rowSplit', 'columnSplice', 'dense', 'dense', 'dense', 'training'],
    ['dataset', 'rowSplit', 'columnSplice', 'dense', 'dense', 'dense', 'training'],
    ['dataset', 'rowSplit', 'columnSplice', 'dense', 'dense', 'dense', 'training'],
    ['dataset', 'rowSplit', 'columnSplice', 'dense', 'dense', 'dense', 'training'],
    ['dataset', 'rowSplit', 'columnSplice', 'dense', 'dense', 'dense', 'training'],
    ['dataset', 'rowSplit', 'columnSplice', 'dense', 'dense', 'dense', 'training'],
    ['dataset', 'rowSplit', 'columnSplice', 'dense', 'dense', 'dense', 'training'],
    ['dataset', 'rowSplit', 'columnSplice', 'dense', 'dense', 'dense', 'training'],
    ['dataset', 'rowSplit', 'columnSplice', 'dense', 'dense', 'dense', 'training'],
    ['dataset', 'rowSplit', 'columnSplice', 'dense', 'dense', 'dense', 'training'],
    ['dataset', 'rowSplit', 'columnSplice', 'dense', 'dense', 'dense', 'training'],
    ['dataset', 'rowSplit', 'columnSplice', 'dense', 'dense', 'dense', 'training'],
    ['dataset', 'rowSplit', 'columnSplice', 'dense', 'dense', 'dense', 'training'],
    ['dataset', 'rowSplit', 'columnSplice', 'dense', 'dense', 'dense', 'training'],
    ['dataset', 'rowSplit', 'columnSplice', 'dense', 'dense', 'dense', 'training'],
    ['dataset', 'rowSplit', 'columnSplice', 'dense', 'dense', 'dense', 'training'],
    ['dataset', 'rowSplit', 'columnSplice', 'dense', 'dense', 'dense', 'training'],
];
