import { LayerType } from "./domain";

export const trainingData: LayerType[][] = [
    ['launcher', 'manualDataEntry', 'transformer', 'dataViewer'],
    ['launcher', 'manualDataEntry', 'transformer', 'dataViewer'],
    ['launcher', 'manualDataEntry', 'transformer', 'dataViewer'],
    ['launcher', 'manualDataEntry', 'transformer', 'dataViewer'],
    ['launcher', 'manualDataEntry', 'transformer', 'dataViewer'],
    ['launcher', 'manualDataEntry', 'transformer', 'transformer', 'dataViewer'],
    ['launcher', 'manualDataEntry', 'transformer', 'transformer', 'dataViewer'],
    ['launcher', 'manualDataEntry', 'transformer', 'transformer', 'dataViewer'],
    ['launcher', 'manualDataEntry', 'transformer', 'transformer', 'dataViewer'],
    ['launcher', 'manualDataEntry', 'transformer', 'transformer', 'dataViewer'],
    ['dataset', 'rowSplit', 'columnSplit', 'training'],
    ['dataset', 'rowSplit', 'columnSplit', 'training'],
    ['dataset', 'rowSplit', 'columnSplit', 'training'],
    ['dataset', 'rowSplit', 'columnSplit', 'training'],
    ['dataset', 'rowSplit', 'columnSplit', 'training'],
    ['dataset', 'rowSplit', 'columnSplit', 'dense', 'dense', 'training'],
    ['dataset', 'rowSplit', 'columnSplit', 'dense', 'dense', 'training'],
    ['dataset', 'rowSplit', 'columnSplit', 'dense', 'dense', 'training'],
    ['dataset', 'rowSplit', 'columnSplit', 'dense', 'dense', 'training'],
    ['dataset', 'rowSplit', 'columnSplit', 'dense', 'dense', 'training'],
    ['dataset', 'rowSplit', 'columnSplit', 'dense', 'dense', 'training'],
    ['dataset', 'rowSplit', 'columnSplit', 'dense', 'dense', 'training'],
    ['dataset', 'rowSplit', 'columnSplit', 'dense', 'dense', 'dense', 'training'],
    ['dataset', 'rowSplit', 'columnSplit', 'dense', 'dense', 'dense', 'training'],
    ['dataset', 'rowSplit', 'columnSplit', 'dense', 'dense', 'dense', 'training'],
    ['dataset', 'rowSplit', 'columnSplit', 'dense', 'dense', 'dense', 'training'],
    ['dataset', 'rowSplit', 'columnSplit', 'dense', 'dense', 'dense', 'training'],
    ['dataset', 'rowSplit', 'columnSplit', 'dense', 'dense', 'dense', 'training'],
    ['dataset', 'rowSplit', 'columnSplit', 'dense', 'dense', 'dense', 'training'],
    ['dataset', 'rowSplit', 'columnSplit', 'dense', 'dense', 'dense', 'training'],
    ['dataset', 'rowSplit', 'columnSplit', 'dense', 'dense', 'dense', 'training'],
    ['dataset', 'rowSplit', 'columnSplit', 'dense', 'dense', 'dense', 'training'],
    ['dataset', 'rowSplit', 'columnSplit', 'dense', 'dense', 'dense', 'training'],
    ['dataset', 'rowSplit', 'columnSplit', 'dense', 'dense', 'dense', 'training'],
    ['dataset', 'rowSplit', 'columnSplit', 'dense', 'dense', 'dense', 'training'],
    ['dataset', 'rowSplit', 'columnSplit', 'dense', 'dense', 'dense', 'training'],
    ['dataset', 'rowSplit', 'columnSplit', 'dense', 'dense', 'dense', 'training'],
    ['dataset', 'rowSplit', 'columnSplit', 'dense', 'dense', 'dense', 'training'],
    ['dataset', 'rowSplit', 'columnSplit', 'dense', 'dense', 'dense', 'training'],
    ['dataset', 'rowSplit', 'columnSplit', 'dense', 'dense', 'dense', 'training'],
    ['dataset', 'rowSplit', 'columnSplice', 'training'],
    ['dataset', 'rowSplit', 'columnSplice', 'training'],
    ['dataset', 'rowSplit', 'columnSplice', 'training'],
    ['dataset', 'rowSplit', 'columnSplice', 'training'],
    ['dataset', 'rowSplit', 'columnSplice', 'training'],
    ['dataset', 'rowSplit', 'columnSplice', 'dense', 'dense', 'training'],
    ['dataset', 'rowSplit', 'columnSplice', 'dense', 'dense', 'training'],
    ['dataset', 'rowSplit', 'columnSplice', 'dense', 'dense', 'training'],
    ['dataset', 'rowSplit', 'columnSplice', 'dense', 'dense', 'training'],
    ['dataset', 'rowSplit', 'columnSplice', 'dense', 'dense', 'training'],
    ['dataset', 'rowSplit', 'columnSplice', 'dense', 'dense', 'training'],
    ['dataset', 'rowSplit', 'columnSplice', 'dense', 'dense', 'training'],
    ['dataset', 'rowSplit', 'columnSplice', 'dense', 'dense', 'dense', 'training'],
    ['dataset', 'rowSplit', 'columnSplice', 'dense', 'dense', 'dense', 'training'],
    ['dataset', 'rowSplit', 'columnSplice', 'dense', 'dense', 'dense', 'training'],
    ['dataset', 'rowSplit', 'columnSplice', 'dense', 'dense', 'dense', 'training'],
    ['dataset', 'rowSplit', 'columnSplice', 'dense', 'dense', 'dense', 'training'],
    ['dataset', 'rowSplit', 'columnSplice', 'dense', 'dense', 'dense', 'training'],
    ['dataset', 'rowSplit', 'columnSplice', 'dense', 'dense', 'dense', 'training'],
    ['dataset', 'rowSplit', 'columnSplice', 'dense', 'dense', 'dense', 'training'],
    ['dataset', 'rowSplit', 'columnSplice', 'dense', 'dense', 'dense', 'training'],
    ['dataset', 'rowSplit', 'columnSplice', 'dense', 'dense', 'dense', 'training'],
    ['dataset', 'rowSplit', 'columnSplice', 'dense', 'dense', 'dense', 'training'],
    ['dataset', 'rowSplit', 'columnSplice', 'dense', 'dense', 'dense', 'training'],
    ['dataset', 'rowSplit', 'columnSplice', 'dense', 'dense', 'dense', 'training'],
    ['dataset', 'rowSplit', 'columnSplice', 'dense', 'dense', 'dense', 'training'],
    ['dataset', 'rowSplit', 'columnSplice', 'dense', 'dense', 'dense', 'training'],
    ['dataset', 'rowSplit', 'columnSplice', 'dense', 'dense', 'dense', 'training'],
    ['dataset', 'rowSplit', 'columnSplice', 'dense', 'dense', 'dense', 'training'],
    ['dataset', 'rowSplit', 'columnSplice', 'dense', 'dense', 'dense', 'training'],
];
